Initial commit

diff --git a/dot_shtils b/dot_shtils
--- a/dot_shtils
+++ b/dot_shtils
@@ -1,5 +1,24 @@
 #!/bin/sh
 
+pathmunge() {
+  if ! echo "${PATH}" | grep -Eq "(^|:)$1($|:)" ; then
+     if [ "${2}" = "after" ] ; then
+      PATH="${PATH}:${1}"
+     else
+      PATH="${1}:${PATH}"
+     fi
+  fi
+}
+
+if [ -z "${DEVBIN}" ]; then
+  echo "DEVBIN not set, checking if DEVBIN dir exists"
+  if [ ! -d "${HOME}/.devbin" ]; then
+    echo "DEVBIN dir does not exist, custom functions will fail"
+  else
+    pathmunge "${HOME}/.devbin"
+  fi
+fi
+
 # Tmux sessions
 alias default='new_or_switch_tab default ${HOME}'
 alias misc='default'
diff --git a/exact_dot_devbin/executable_fz b/exact_dot_devbin/executable_fz
--- a/exact_dot_devbin/executable_fz
+++ b/exact_dot_devbin/executable_fz
@@ -9,11 +9,11 @@ __kill_process () {
     CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1 | grep "load" | wc -l)
     if [ ${CAN_I_RUN_SUDO} -gt 0 ]
     then
-        echo "I can run the sudo command"
-        echo $pid | xargs kill -${1:-9}
+      echo-info "I can run the sudo command"
+      echo $pid | xargs kill -${1:-9}
     else
-        echo "I can't run the Sudo command"
-        echo $pid | xargs sudo kill -${1:-9}
+      echo-info "I can't run the sudo command"
+      echo $pid | xargs sudo kill -${1:-9}
     fi
     __kill_process
   fi
@@ -75,7 +75,7 @@ while (( "$#" )); do
       shift
       ;;
     -*|--*=) # unsupported flags
-      echo "Error: Unsupported flag $1" >&2
+      echo-err "Unsupported flag $1" >&2
       exit 1
       ;;
     *) # preserve positional arguments
@@ -105,8 +105,7 @@ case $fzf_command in
     __search_edit
     ;;
   *)
-    echo "Error: Unsupported command $1" >&2
+    echo-err "Unsupported command $1" >&2
     exit 1
     ;;
 esac
-
