patch: Convert bash to POSIX sh

diff --git a/exact_dot_devbin/executable_dotfiles b/exact_dot_devbin/executable_dotfiles
--- a/exact_dot_devbin/executable_dotfiles
+++ b/exact_dot_devbin/executable_dotfiles
@@ -10,38 +10,41 @@ Usage:
 
 command="$1"
 if [ -z "$command" ]; then
-  echo "$usage"
-  exit 1
+	echo "$usage"
+	exit 1
 fi
 
 shift
 
 case "$command" in
-  -h | --help)
-    echo "$usage"
-    exit
-    ;;
-  apply)
-    cmd="safe-run"
-    for arg in "$@"; do
-      case "$arg" in
-        --noconfirm|--yes) cmd="echo-run"; break ;;
-      esac
-    done
-    if [ "$cmd" = "safe-run" ] && echo-run chezmoi verify; then
-      echo-info "Nothing to apply."
-      exit
-    fi
-    if [ "$cmd" = "safe-run" ] && ! echo-run chezmoi diff --no-pager; then
-      echo-warn "Error showing diff. Are you signed in to 1Password?"
-      exit 1
-    fi
-    if ! "$cmd" chezmoi apply; then
-      echo-info "You can run 'dotfiles add <file>...' to update the source."
-      exit
-    fi
-    ;;
-  *)
-    echo-run chezmoi "$command" "$@"
-    ;;
+-h | --help)
+	echo "$usage"
+	exit
+	;;
+apply)
+	cmd="safe-run"
+	for arg in "$@"; do
+		case "$arg" in
+		--noconfirm | --yes)
+			cmd="echo-run"
+			break
+			;;
+		esac
+	done
+	if [ "$cmd" = "safe-run" ] && echo-run chezmoi verify; then
+		echo-info "Nothing to apply."
+		exit
+	fi
+	if [ "$cmd" = "safe-run" ] && ! echo-run chezmoi diff --no-pager; then
+		echo-warn "Error showing diff. Are you signed in to 1Password?"
+		exit 1
+	fi
+	if ! "$cmd" chezmoi apply; then
+		echo-info "You can run 'dotfiles add <file>...' to update the source."
+		exit
+	fi
+	;;
+*)
+	echo-run chezmoi "$command" "$@"
+	;;
 esac
